---
- hosts: server
  become: yes
  gather_facts: yes

  vars_files:
    - ../vars/secrets.yml

  roles:
    - role: ../roles/geerlingguy.nginx
      tags: setup

  tasks:
    - name: Setup Nginx
      import_tasks: tasks/setup_nginx.yml
      tags: setup

    - name: Restart Nginx
      import_tasks: tasks/restart_nginx.yml
      tags: restart
