---
- name: Create file domain.conf
  template:
    src: ../templates/nginx_config.j2
    dest: /etc/nginx/sites-available/{{ domain }}.conf

- name: Create symbolic link to sites-enabled
  file:
    src: /etc/nginx/sites-available/{{ domain }}.conf
    dest: /etc/nginx/sites-enabled/{{ domain }}.conf
    state: link
